name: CI
on: [push]

jobs:
  spec:
    name: Spec
    runs-on: ubuntu-20.04
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: crystallang/crystal:1.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Shards install
        run: shards install

      - name: Spec
        run: crystal spec --no-color --order random
