name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'shard.yml'
      - 'shard.lock'
      - 'src/**'
      - 'spec/**'

jobs:
  spec:
    name: Spec
    runs-on: ubuntu-20.04
    steps:
      - name: Install RabbitMQ
        run: sudo apt-get update && sudo apt-get install -y rabbitmq-server

      - name: Verify RabbitMQ started correctly
        run: while true; do sudo rabbitmq-diagnostics status 2>/dev/null && break; echo -n .; sleep 2; done

      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install shards
        run: shards install

      - name: Run tests
        run: crystal spec --no-color --order random
