on:
  push:
    tags:
      - v*

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: git clone ${{ github.repositoryUrl }} .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build static tar package
        uses: docker/build-push-action@v3
        with:
          file: tar.Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: .

      - name: Create Release
        run: gh release create "${{ github.ref }}" ./*.tar.gz --notes "$(./build/release_notes)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
